describe('template spec', () => {
    it('Register test failed 1 part all failed', () => {
        cy.fixture('newCypressTest').then(data => {
            cy.visit('https://dev.profteam.su/registration')
            cy.log('Ввод некорректного логина')
            cy.get(':nth-child(1) > :nth-child(1) > .form-control--medium > .form-input--text').type(data.none_existent_login)
            cy.log('Ввод некорректного email')
            cy.get('.form-input--email').type(data.none_existent_email)
            cy.log('Ввод некорректного пароля')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--password').type(data.none_existent_password)
            cy.get(':nth-child(4) > .form-control--medium > .form-input--password').type(data.none_existent_password)
        })
    })

    it('Register test failed 1 part login failed', () => {
        cy.fixture('newCypressTest').then(data => {
            cy.visit('https://dev.profteam.su/registration')
            cy.log('Ввод некорректного логина')
            cy.get(':nth-child(1) > :nth-child(1) > .form-control--medium > .form-input--text').type(data.none_existent_login)
            cy.log('Ввод корректного email')
            cy.get('.form-input--email').type(data.email)
            cy.log('Ввод корректного пароля')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--password').type(data.password)
            cy.get(':nth-child(4) > .form-control--medium > .form-input--password').type(data.password)
        })
    })

    it('Register test failed 1 part email failed', () => {
        cy.fixture('newCypressTest').then(data => {
            cy.visit('https://dev.profteam.su/registration')
            cy.log('Ввод корректного логина')
            cy.get(':nth-child(1) > :nth-child(1) > .form-control--medium > .form-input--text').type(data.login)
            cy.log('Ввод некорректного email')
            cy.get('.form-input--email').type(data.none_existent_email)
            cy.log('Ввод корректного пароля')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--password').type(data.password)
            cy.get(':nth-child(4) > .form-control--medium > .form-input--password').type(data.password)
        })
    })

    it('Register test failed 1 part password failed', () => {
        cy.fixture('newCypressTest').then(data => {
            cy.visit('https://dev.profteam.su/registration')
            cy.log('Ввод корректного логина')
            cy.get(':nth-child(1) > :nth-child(1) > .form-control--medium > .form-input--text').type(data.login)
            cy.log('Ввод корректного email')
            cy.get('.form-input--email').type(data.email)
            cy.log('Ввод некорректного пароля')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--password').type(data.none_existent_password)
            cy.get(':nth-child(4) > .form-control--medium > .form-input--password').type(data.none_existent_password)
        })
    })

    it('Register test failed 1 part password and login failed', () => {
        cy.fixture('newCypressTest').then(data => {
            cy.visit('https://dev.profteam.su/registration')
            cy.log('Ввод некорректного логина')
            cy.get(':nth-child(1) > :nth-child(1) > .form-control--medium > .form-input--text').type(data.none_existent_login)
            cy.log('Ввод корректного email')
            cy.get('.form-input--email').type(data.email)
            cy.log('Ввод некорректного пароля')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--password').type(data.none_existent_password)
            cy.get(':nth-child(4) > .form-control--medium > .form-input--password').type(data.none_existent_password)
        })
    })

    it('Register test failed 1 part password and email failed', () => {
        cy.fixture('newCypressTest').then(data => {
            cy.visit('https://dev.profteam.su/registration')
            cy.log('Ввод корректного логина')
            cy.get(':nth-child(1) > :nth-child(1) > .form-control--medium > .form-input--text').type(data.login)
            cy.log('Ввод некорректного email')
            cy.get('.form-input--email').type(data.none_existent_email)
            cy.log('Ввод некорректного пароля')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--password').type(data.none_existent_password)
            cy.get(':nth-child(4) > .form-control--medium > .form-input--password').type(data.none_existent_password)
        })
    })

    it('Register test failed 1 part login and email failed', () => {
        cy.fixture('newCypressTest').then(data => {
            cy.visit('https://dev.profteam.su/registration')
            cy.log('Ввод некорректного логина')
            cy.get(':nth-child(1) > :nth-child(1) > .form-control--medium > .form-input--text').type(data.none_existent_login)
            cy.log('Ввод некорректного email')
            cy.get('.form-input--email').type(data.none_existent_email)
            cy.log('Ввод корректного пароля')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--password').type(data.password)
            cy.get(':nth-child(4) > .form-control--medium > .form-input--password').type(data.password)
        })
    })


    it('Register test failed 2 part', () => {
        cy.fixture('newCypressTest').then(data => {
            cy.visit('https://dev.profteam.su/registration')
            cy.log('Ввод некорректного логина')
            cy.get(':nth-child(1) > :nth-child(1) > .form-control--medium > .form-input--text').type(data.login)
            cy.log('Ввод корректного email')
            cy.get('.form-input--email').type(data.email)
            cy.log('Ввод некорректного пароля')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--password').type(data.password)
            cy.get(':nth-child(4) > .form-control--medium > .form-input--password').type(data.password)
            cy.log('Клик по кнопке')
            cy.get(':nth-child(4) > .button').click()
            cy.log('Ввод некорректной фамилия')
            cy.get('[style=""] > :nth-child(1) > .form-control--medium > .form-input--text').type(data.none_existent_name)
            cy.log('Ввод некорректного имя')
            cy.get(':nth-child(2) > .form-control--medium > .form-input--text').type(data.none_existent_surname)
            cy.log('Ввод некорректного отчества ')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--text').type(data.none_existent_patronymic)
        })
    })

    it('Register test failed 2 part name failed', () => {
        cy.fixture('newCypressTest').then(data => {
            cy.visit('https://dev.profteam.su/registration')
            cy.log('Ввод некорректного логина')
            cy.get(':nth-child(1) > :nth-child(1) > .form-control--medium > .form-input--text').type(data.login)
            cy.log('Ввод корректного email')
            cy.get('.form-input--email').type(data.email)
            cy.log('Ввод некорректного пароля')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--password').type(data.password)
            cy.get(':nth-child(4) > .form-control--medium > .form-input--password').type(data.password)
            cy.log('Клик по кнопке')
            cy.get(':nth-child(4) > .button').click()
            cy.log('Ввод некорректной фамилия')
            cy.get('[style=""] > :nth-child(1) > .form-control--medium > .form-input--text').type(data.none_existent_name)
            cy.log('Ввод корректного имя')
            cy.get(':nth-child(2) > .form-control--medium > .form-input--text').type(data.surname)
            cy.log('Ввод корректного отчества ')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--text').type(data.patronymic)
        })
    })

    it('Register test failed 2 part surname failed', () => {
        cy.fixture('newCypressTest').then(data => {
            cy.visit('https://dev.profteam.su/registration')
            cy.log('Ввод некорректного логина')
            cy.get(':nth-child(1) > :nth-child(1) > .form-control--medium > .form-input--text').type(data.login)
            cy.log('Ввод корректного email')
            cy.get('.form-input--email').type(data.email)
            cy.log('Ввод некорректного пароля')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--password').type(data.password)
            cy.get(':nth-child(4) > .form-control--medium > .form-input--password').type(data.password)
            cy.log('Клик по кнопке')
            cy.get(':nth-child(4) > .button').click()
            cy.log('Ввод корректной фамилия')
            cy.get('[style=""] > :nth-child(1) > .form-control--medium > .form-input--text').type(data.name)
            cy.log('Ввод некорректного имя')
            cy.get(':nth-child(2) > .form-control--medium > .form-input--text').type(data.none_existent_surname)
            cy.log('Ввод корректного отчества ')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--text').type(data.patronymic)
        })
    })

    it('Register test failed 2 part patronymic failed', () => {
        cy.fixture('newCypressTest').then(data => {
            cy.visit('https://dev.profteam.su/registration')
            cy.log('Ввод некорректного логина')
            cy.get(':nth-child(1) > :nth-child(1) > .form-control--medium > .form-input--text').type(data.login)
            cy.log('Ввод корректного email')
            cy.get('.form-input--email').type(data.email)
            cy.log('Ввод некорректного пароля')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--password').type(data.password)
            cy.get(':nth-child(4) > .form-control--medium > .form-input--password').type(data.password)
            cy.log('Клик по кнопке')
            cy.get(':nth-child(4) > .button').click()
            cy.log('Ввод корректной фамилия')
            cy.get('[style=""] > :nth-child(1) > .form-control--medium > .form-input--text').type(data.name)
            cy.log('Ввод корректного имя')
            cy.get(':nth-child(2) > .form-control--medium > .form-input--text').type(data.surname)
            cy.log('Ввод некорректного отчества ')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--text').type(data.none_existent_patronymic)
        })
    })

    it('Register test failed 2 part patronymic and name failed', () => {
        cy.fixture('newCypressTest').then(data => {
            cy.visit('https://dev.profteam.su/registration')
            cy.log('Ввод некорректного логина')
            cy.get(':nth-child(1) > :nth-child(1) > .form-control--medium > .form-input--text').type(data.login)
            cy.log('Ввод корректного email')
            cy.get('.form-input--email').type(data.email)
            cy.log('Ввод некорректного пароля')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--password').type(data.password)
            cy.get(':nth-child(4) > .form-control--medium > .form-input--password').type(data.password)
            cy.log('Клик по кнопке')
            cy.get(':nth-child(4) > .button').click()
            cy.log('Ввод некорректной фамилия')
            cy.get('[style=""] > :nth-child(1) > .form-control--medium > .form-input--text').type(data.none_existent_name)
            cy.log('Ввод корректного имя')
            cy.get(':nth-child(2) > .form-control--medium > .form-input--text').type(data.surname)
            cy.log('Ввод некорректного отчества ')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--text').type(data.none_existent_patronymic)
        })
    })

    it('Register test failed 2 part patronymic and surname failed', () => {
        cy.fixture('newCypressTest').then(data => {
            cy.visit('https://dev.profteam.su/registration')
            cy.log('Ввод некорректного логина')
            cy.get(':nth-child(1) > :nth-child(1) > .form-control--medium > .form-input--text').type(data.login)
            cy.log('Ввод корректного email')
            cy.get('.form-input--email').type(data.email)
            cy.log('Ввод некорректного пароля')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--password').type(data.password)
            cy.get(':nth-child(4) > .form-control--medium > .form-input--password').type(data.password)
            cy.log('Клик по кнопке')
            cy.get(':nth-child(4) > .button').click()
            cy.log('Ввод корректной фамилия')
            cy.get('[style=""] > :nth-child(1) > .form-control--medium > .form-input--text').type(data.name)
            cy.log('Ввод некорректного имя')
            cy.get(':nth-child(2) > .form-control--medium > .form-input--text').type(data.none_existent_surname)
            cy.log('Ввод некорректного отчества ')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--text').type(data.none_existent_patronymic)
        })
    })

    it('Register test failed 2 part name and surname failed', () => {
        cy.fixture('newCypressTest').then(data => {
            cy.visit('https://dev.profteam.su/registration')
            cy.log('Ввод некорректного логина')
            cy.get(':nth-child(1) > :nth-child(1) > .form-control--medium > .form-input--text').type(data.login)
            cy.log('Ввод корректного email')
            cy.get('.form-input--email').type(data.email)
            cy.log('Ввод некорректного пароля')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--password').type(data.password)
            cy.get(':nth-child(4) > .form-control--medium > .form-input--password').type(data.password)
            cy.log('Клик по кнопке')
            cy.get(':nth-child(4) > .button').click()
            cy.log('Ввод некорректной фамилия')
            cy.get('[style=""] > :nth-child(1) > .form-control--medium > .form-input--text').type(data.none_existent_name)
            cy.log('Ввод некорректного имя')
            cy.get(':nth-child(2) > .form-control--medium > .form-input--text').type(data.none_existent_surname)
            cy.log('Ввод корректного отчества ')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--text').type(data.patronymic)
        })
    })
})